services:
  - type: web
    name: ethio-shopify-api
    runtime: ruby
    rootDir: backend_api
    region: ohio
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "rails server -b 0.0.0.0 -p $PORT"
    healthCheckPath: /up
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: RAILS_LOG_TO_STDOUT
        value: "true"
      - key: PORT
        value: "10000"
